// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/menu": {
    params: {};
  };
  "/order": {
    params: {};
  };
  "/reservations": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/contact": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/menu" | "/order" | "/reservations" | "/about" | "/contact";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/menu.tsx": {
    id: "routes/menu";
    page: "/menu";
  };
  "routes/order.tsx": {
    id: "routes/order";
    page: "/order";
  };
  "routes/reservations.tsx": {
    id: "routes/reservations";
    page: "/reservations";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
};